name: riverpod_community_extensions
description: Extends Riverpod ref types with additional helpers, to easily add common functionalities to your providers.
version: 0.1.1
homepage: https://github.com/bamlab/riverpod_community_extensions
repository: https://github.com/bamlab/riverpod_community_extensions
issue_tracker: https://github.com/bamlab/riverpod_community_extensions/issues

environment:
  sdk: ">=3.6.0 <4.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  melos: ^7.1.1
  mocktail: ^1.0.0
  theodo_analysis: ^1.6.0

dependencies:
  connectivity_plus: ^6.0.3
  flutter:
    sdk: flutter
  riverpod: ">=2.6.1 <3.0.0"
